[package]
name = "rust_game"
version = "0.1.0"
edition = "2018"
authors = ["Random guy <ikigami.business@gmail.com>"]
license = "AFPL"
description = "A JRPG made in Rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
toml = "0.5.8"
# below are libraries used and made by me
render = { path = "./src/render", version = "0.1.0"}
items = { path = "./src/items", version = "0.1.0" }
user-interfaces = { path = "./src/user-interfaces", version = "0.1.0" }
world-interaction = { path = "./src/world-interaction", version = "0.1.0" }


[workspace]
