[package]
name = "atg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindgen = "0.59.2"
bytes = "1.1.0"
check-if-email-exists = "0.8.25"
chrono = "0.4.19"
cmake = "0.1.46"
config = "0.11.0"
configparser = "3.0.0"
directories = "4.0.1"
fastrand = "1.5.0"
flexi_logger = "0.20.1"
futures = { version = "0.3.18", default-features = false }
git-version = "0.3.5"
glam = "0.20.1"
humantime = "2.1.0"
jni = "0.19.0"
keyring = "1.0.0"
laminar = "0.5.0"
lazy_static = "1.4.0"
lettre = "0.10.0-rc.4"
log = "0.4.14"
mailchecker = "4.1.3"
mio = "0.8.0"
quick-xml = "0.22.0"
quinn = "0.8.0"
rand = "0.8.4"
regex = "1.5.4"
rg3d = { git = "https://github.com/rg3dengine/rg3d" }
ron = "0.7.0"
savefile = "0.8.3"
serde = { version = "1.0.130", features = ["derive"] }
serde_any = "0.5.0"
serde_json = "1.0.72"
serde_yaml = "0.8.21"
socket2 = "0.4.2"
structopt = "0.3.25"
time = "0.3.5"
tokio = "1.14.0"
toml = "0.5.8"
tracing = "0.1.29"
tracing-subscriber = "0.3.3"
uuid = { version = "0.8.2", features = ["v4"] }
warp = "0.3.2"
yup-oauth2 = "6.1.0"
