[package]
name = "atg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
member = [
	"AscendingToGodhood",
	"client",
	"common",
	"common/logging",
	"common/net",
	"network",
	"network/protocol",
	"plugin",
	"server",
	"server-cli",
	"world",
]