cargo-features = ["named-profiles","profile-overrides"]

[workspace]
members = [
	"AscendingToGodhood",
	"client",
	"common",
	"common/logging",
	"common/net",
	"network",
	"network/protocol",
	"plugin",
	"server",
	"server-cli",
	"world",
]
