[package]
name = "atg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rg3d = { git = "https://github.com/rg3dengine/rg3d", rev = "" }
savefile = "0.8.3"
ron = "0.7.0"
quinn = "0.8.0" # for multiplayer
structopt = "0.3.13"

[[bin]]
name = "log"
path = "src/bin/logiso.rs"

[[bin]]
name = "crha"
path = "src/bin/crash-handler.rs"