[package]
name = "atg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rg3d = "0.23.1" # { git = "https://github.com/rg3dengine/rg3d" }
savefile = "0.8.3"
ron = "0.7.0"
quinn = "0.8.0"
structopt = "0.3.25"
serde = { version = "1.0.130", features = ["derive"] }
serde_any = "0.5.0"
glam = "0.20.1"
laminar = "0.5.0"
tokio = "1.14.0"
regex = "1.5.4"
rand = "0.8.4"
fastrand = "1.5.0"
log = "0.4.14"
mio = "0.8.0"
lazy_static = "1.4.0"
git-version = "0.3.5"
cmake = "0.1.46"
bindgen = "0.59.2"
jni = "0.19.0"
mailchecker = "4.1.3"
check-if-email-exists = "0.8.25"
lettre = "0.10.0-rc.4"
tracing-subscriber = "0.3.3"
tracing = "0.1.29"
flexi_logger = "0.20.1"
yup-oauth2 = "6.1.0"
keyring = "1.0.0"
socket2 = "0.4.2"
chrono = "0.4.19"
directories = "4.0.1"
humantime = "2.1.0"
time = "0.3.5"
serde_json = "1.0.72"
serde_yaml = "0.8.21"
toml = "0.5.8"
quick-xml = "0.22.0"
config = "0.11.0"
configparser = "3.0.0"

[[bin]]
name = "log"
path = "src/bin/logiso.rs"

[[bin]]
name = "crha"
path = "src/bin/crash-handler.rs"
