[package]
name = "data"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rg3d = "0.23.1"
# savefile = "0.8.3"
# ron = "0.7.0"
# quinn = "*" # for multiplayer 
