[alias]
ch = "check"
chr = "check --release"
b = "build"
br = "build --release"
r = "run"
rr = "run --release"
cl = "clean"
t = "test"
updep = "upgrade"
uplock = "update"
e = "build --examples"
er = "build --examples --release"

[build]
target-dir = "build"
incremental = true
rustflags = ["-C", "link-args=-fuse-ld=lld"]

[doc]
no-deps = true
