[package]
name = "CreatureLib"
version = "0.1.0"
edition = "2021"
description = "The crate which contain all the information needed for npc existence"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ron = "*"
