name: release a new version/bug fix

on:
  pull_request:
    branches: 
      - release
    branches-ignore:
      - '*'
  pull_request_target:
    branches:
      - master-(racism)
    branches-ignore: 
      - '*'

jobs:
  release:
